apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapidockerproject-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WebApiDockerProject
  template:
    metadata:
      labels:
        app: WebApiDockerProject
    spec:
      containers:
      - name: webapidockerprojectrepos
<<<<<<< HEAD
        image: samplecr4.azurecr.io/practicecheckrepos:latest
=======
        image: samplecr1.azurecr.io/webapidockerprojectrepos:latest
>>>>>>> 443c446ec9a5f14d17ecc2548489146427b0867a
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn2

---
apiVersion: v1
kind: Service
metadata:
  name: webapidockerproject
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: WebApiDockerProject
